# Generated by Django 5.2 on 2025-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_distance_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, help_text='Accumulative total of distances traveled. In kilometers.', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed relative to the previous position, based on time and distance traveled. In meters per second.', null=True),
        ),
    ]
