# Generated by Django 5.2 on 2025-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_alter_position_distance_alter_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, help_text='Average speed. In meters per second.', null=True),
        ),
    ]
